name: expense_tracker
description: A new Flutter project.

publish_to: "none"

environment:
  sdk: ">=2.18.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.0.0
  go_router: ^7.0.0
  hive_flutter: ^1.1.0
  fl_chart: ^0.60.0
  path_provider: ^2.0.11

ddev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.0
  build_runner: ^2.4.0

  
flutter:
  uses-material-design: true
